# list[start:end:step]
data = "ATGTGCATGGAAATCTGTCGAGACCCGAGCTGGTGGCCTCATCGTAACTGCGGCTGGGTTGACGATTCTTGCCGCACACGTTAACGAGATAACGGGTAACGTTCGGAACCGACGTCTGCGCCCGGTTAGACACGCCGTTCCGTATTAGCTGTAATGACCTTGATAACATTAGAGATCTCAAACGGAGAGTAAGAAGATCCCTGGTCTTAGCTCGACCCTCGTGAGCGACTCCACTTTACGGGGTATCAGCGAAATTAAACTATCCGACTCAATGCAAGACTGGCGCCGTGGGGCGATGGCCGGTATCGGGACACGGCCTAAGTCCGGATCCCGCGCCTCACCCTTTTTGGTGAAGTCCCCTCTGTTCTAACTCTTCTAGCCAGTGTGCCCCAGGTGTGTGGCAGTGACCCAGTATAGACGTTTCCTCAGACCAATTTGGACGACCTAGGAGTTGGTGCTGCAACCAAGATTCAGGTCCAGGCCGCCTGTCTCGCCCGCTCCCTGCTGATTCTAAAGTCGCGTGGACTCTAGTATTCACACAGCGCACAACTAAGATAGACTTAAGGACAACTCTCGACCTTGTTCTTATAGGTCTAGTATCTGCTCGTGATAACGTCGCGAGTCTCGGCATTTACTCTGCCAGCTAGTTAGACTTAGCTTGCTAGTTAATTCCATCGCAGTGGTAATGTCGAATGCTCCCGTGTTAAGGGACTCGGAGGTCGCCCGTTCGAGCACCGTGTGGCGATCTGCTGTCCGTCCTTTGCGCAGCTTTCCGCCAGTGACCTCCGACGCCGCAATACCCATTCGTAGGAATTGACTATGAGACATGCGTAAGAGCCCAACACACAGCTTATTGGGCGCCTTCTTTGTGTGCCATGCTTAAAGTTGAGATATTTTAATAACACATCCGGTTGTTTTGCGTGACCCTCATCGCCCCTCGGGGTACCGCAGCCGCAGTACTAACC"

def complement(s: str):
    tmp = ''
    for nuc in s:
        if nuc == 'A': tmp += 'T'
        elif nuc == 'T': tmp += 'A'
        elif nuc == 'C': tmp += 'G'
        elif nuc == 'G': tmp += 'C'
    return tmp

tmpdata = data[::-1]
tmpdata = complement(tmpdata)

print(tmpdata)

